spring:
  main:
    banner-mode: off
server:
  port: ${NCANODE_PORT:14579}
ncanode:
  system:
    detailedErrors: ${NCANODE_DEBUG:false}
    cacheDir: ${NCANODE_CACHE_DIR:./cache}
  crl:
    enabled: ${NCANODE_CRL_ENABLED:true}
    ttl: ${NCANODE_CRL_TTL:1440}
  http-client:
    connectionTtl: ${NCANODE_HTTP_CLIENT_CONNECTION_TTL:10}
    userAgent: ${NCANODE_HTTP_CLIENT_USER_AGENT:}
    proxy:
      url: ${NCANODE_PROXY_URL:}
      username: ${NCANODE_PROXY_USERNAME:}
      password: ${NCANODE_PROXY_PASSWORD:}
