spring:
  main:
    banner-mode: off
server:
  port: ${NCANODE_PORT:14579}
ncanode:
  system:
    detailedErrors: ${NCANODE_DEBUG:false}
    cacheDir: ${NCANODE_CACHE_DIR:./cache}
  crl:
    enabled: ${NCANODE_CRL_ENABLED:true}
    ttl: ${NCANODE_CRL_TTL:1440}
