name: Build CI and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Install kalkan libraries
        env:
          KALKAN_CRYPT_URL: ${{ secrets.KALKAN_CRYPT_URL }}
          KALKAN_CRYPT_XMLDSIG_URL: ${{ secrets.KALKAN_CRYPT_XMLDSIG_URL }}
        run: |
          wget -P ./lib "$KALKAN_CRYPT_URL"
          wget -P ./lib "$KALKAN_CRYPT_XMLDSIG_URL"
      - name: Build and Run tests
        run: ./gradlew clean test
